### PR TITLE
Add ignore rules for generated files

### PR DESCRIPTION
**Pull request by Dinistro**
Adds ignore rules to ensure that paper.pdf and other generated files aren't commited by accident. 

Note that I couldn't execute make, as the build is currently broken on the master branch.

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
@Dinistro, thanks for the patch. We certainly want to exclude latex temporary files and the automatically built *.pdf documents. Your patch achieves this very well!

In addition, it seems to ignore any other *.pdf in the repository (see e.g., https://stackoverflow.com/questions/3637660/how-to-exclude-file-only-from-root-folder-in-git). This means that also any figure added as `images/figure.pdf` would be ignored. I feel that is not desirable.

Would it make sense to make these rules only apply to the root folder, by changing the patch from `*.pdf` to `/*.pdf`?

**Comment by tobiasgrosser** [comment]
I also just fixed the broken built in the repository. If you rebase your patch, CI should be happy again.

**Comment by Dinistro** [comment]
Should be fixed. 

Unfortunately the CI still breaks, but the issue seems to be another.

**Comment by tobiasgrosser** [comment]
I merged it. The error was due that pull-requests not being allowed to create releases. After merging, this all works great.

**Pull request merged**
